version: '3.7'

services:

users:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
    - .:/home/harsh/flask-tdd-docker/project
    ports:
    - 5001:5000
    environment:
    - FLASK_APP=/home/harsh/flask-tdd-docker/project/__init__.py
    - FLASK_ENV=development
    - APP_SETTINGS=project.config.DevelopmentConfig  # new
      